"""
False-merge audit dashboard. Reads reports/false_merge_audit.parquet and
renders a static HTML report that shows cluster-size histogram, FPR, vendor
pair heatmap, and worst false merges.

Run: python -m apps.entity.src.audit_dashboard
"""
from __future__ import annotations

import json
from pathlib import Path
from collections import Counter

import pandas as pd


HTML_HEAD = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8" />
<title>Entity-Resolution — False-Merge Audit</title>
<style>
  body { font: 14px/1.45 ui-sans-serif, system-ui, -apple-system, sans-serif; color:#0f172a; max-width: 1000px; margin: 24px auto; padding: 0 20px; }
  h1 { margin: 0 0 4px; }
  .sub { color: #475569; margin-bottom: 24px; }
  .card { background:white; border:1px solid #e2e8f0; border-radius:12px; padding:18px; margin-bottom:16px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }
  th { background: #f8fafc; font-weight: 600; }
  .TP { color: #047857; font-weight: 600; }
  .FP { color: #c2410c; font-weight: 700; }
  .kpi { display:flex; gap:16px; }
  .kpi div { flex:1; padding: 14px; background: #f8fafc; border-radius: 10px; }
  .kpi .label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
  .kpi .value { font-size: 28px; font-weight: 700; color: #0B2545; margin-top: 4px; }
  .kpi .value.bad { color: #c2410c; }
</style></head><body>
<h1>Entity-Resolution — False-Merge Audit</h1>
<div class="sub">Generated by Splink Fellegi-Sunter pipeline · threshold_match = 0.85</div>

<div class="card">
  <div class="kpi">
    <div><div class="label">Total clusters</div><div class="value">__N_CLUSTERS__</div></div>
    <div><div class="label">True-positive clusters</div><div class="value">__N_TP__</div></div>
    <div><div class="label">False-positive clusters</div><div class="value __FPR_CLASS__">__N_FP__</div></div>
    <div><div class="label">False-merge rate</div><div class="value __FPR_CLASS__">__FPR_PCT__%</div></div>
  </div>
</div>

<div class="card">
  <h3 style="margin-top:0">Cluster-size distribution</h3>
  <table>
    <thead><tr><th>Cluster size</th><th>Count</th><th>Share</th></tr></thead>
    <tbody>__SIZE_ROWS__
    </tbody>
  </table>
</div>

<div class="card">
  <h3 style="margin-top:0">Vendor-pair false-merge heatmap</h3>
  <p class="sub">Counts which vendor pairs contributed to false-merge clusters. The diagonal of a vendor pairing with itself is excluded.</p>
  <table>__VENDOR_HEADER__
    <tbody>__HEATMAP_ROWS__
    </tbody>
  </table>
</div>

<div class="card">
  <h3 style="margin-top:0">20 largest clusters by member count</h3>
  <table>
    <thead><tr><th>cluster_id</th><th>members</th><th>unique pids</th><th>vendors</th><th>status</th></tr></thead>
    <tbody>__WORST_ROWS__
    </tbody>
  </table>
</div>

</body></html>"""


def render(audit_path: Path, er_summary_path: Path, out_path: Path):
    audit = pd.read_parquet(audit_path)
    er = json.load(open(er_summary_path))

    n_clusters = len(audit)
    n_tp = int((audit["status"] == "TP").sum())
    n_fp = int((audit["status"] == "FP").sum())
    fpr = n_fp / max(1, n_clusters)
    fpr_class = "bad" if fpr > 0.02 else ""

    size_counts = audit["n_members"].value_counts().sort_index()
    total = sum(size_counts.values)
    size_rows = []
    for size, count in size_counts.items():
        share = 100 * count / total
        size_rows.append(f"<tr><td>{size}</td><td>{count}</td><td>{share:.1f}%</td></tr>")
    size_rows_html = "\n".join(size_rows)

    fp_audits = audit[audit["status"] == "FP"]
    vendor_pairs = Counter()
    for vendors in fp_audits["vendors_involved"].fillna("").tolist():
        vs = sorted(set(vendors.split(",")))
        for i in range(len(vs)):
            for j in range(i + 1, len(vs)):
                vendor_pairs[(vs[i], vs[j])] += 1
    vendors = sorted({v for pair in vendor_pairs for v in pair})
    vendor_header = "<tr><th></th>" + "".join(f"<th>{v}</th>" for v in vendors) + "</tr>"
    heatmap_rows = []
    for a in vendors:
        cells = [f"<th>{a}</th>"]
        for b in vendors:
            if a == b:
                cells.append("<td>·</td>")
            else:
                c = vendor_pairs.get(tuple(sorted([a, b])), 0)
                cls = "FP" if c > 0 else ""
                cells.append(f"<td class='{cls}'>{c}</td>")
        heatmap_rows.append("<tr>" + "".join(cells) + "</tr>")
    heatmap_rows_html = "\n".join(heatmap_rows) or "<tr><td colspan='4'>no false merges</td></tr>"

    worst = audit.sort_values("n_members", ascending=False).head(20)
    worst_rows = []
    for _, r in worst.iterrows():
        status_cls = "FP" if r["status"] == "FP" else "TP"
        worst_rows.append(f"<tr><td>{r['cluster_id']}</td><td>{r['n_members']}</td>"
                          f"<td>{r['n_unique_pids']}</td>"
                          f"<td>{r['vendors_involved']}</td>"
                          f"<td class='{status_cls}'>{r['status']}</td></tr>")
    worst_rows_html = "\n".join(worst_rows)

    out = HTML_HEAD \
        .replace("__N_CLUSTERS__", str(n_clusters)) \
        .replace("__N_TP__", str(n_tp)) \
        .replace("__N_FP__", str(n_fp)) \
        .replace("__FPR_CLASS__", fpr_class) \
        .replace("__FPR_PCT__", str(round(fpr * 100, 3))) \
        .replace("__SIZE_ROWS__", size_rows_html) \
        .replace("__VENDOR_HEADER__", vendor_header) \
        .replace("__HEATMAP_ROWS__", heatmap_rows_html) \
        .replace("__WORST_ROWS__", worst_rows_html)
    out_path.write_text(out)
    print(f"Wrote audit dashboard: {out_path}")


if __name__ == "__main__":
    base = Path(__file__).resolve().parent.parent
    audit = base / "reports" / "false_merge_audit.parquet"
    er_sum = base / "reports" / "er_summary.json"
    out = base / "reports" / "audit_dashboard.html"
    if not audit.exists():
        print(f"Missing {audit} — run er_engine.py first")
        raise SystemExit(1)
    render(audit, er_sum, out)
